// Code generated by MockGen. DO NOT EDIT.
// Source: capital_adequacy/testing-with-gomock/doer (interfaces: Doer)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	cloudwatch "github.com/aws/aws-sdk-go/service/cloudwatch"
	gomock "github.com/golang/mock/gomock"
)

// MockDoer is a mock of Doer interface
type MockDoer struct {
	ctrl     *gomock.Controller
	recorder *MockDoerMockRecorder
}

// MockDoerMockRecorder is the mock recorder for MockDoer
type MockDoerMockRecorder struct {
	mock *MockDoer
}

// NewMockDoer creates a new mock instance
func NewMockDoer(ctrl *gomock.Controller) *MockDoer {
	mock := &MockDoer{ctrl: ctrl}
	mock.recorder = &MockDoerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDoer) EXPECT() *MockDoerMockRecorder {
	return m.recorder
}

// PutMetricData mocks base method
func (m *MockDoer) PutMetricData(arg0 *cloudwatch.PutMetricDataInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutMetricData", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutMetricData indicates an expected call of PutMetricData
func (mr *MockDoerMockRecorder) PutMetricData(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutMetricData", reflect.TypeOf((*MockDoer)(nil).PutMetricData), arg0)
}
